### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by davivcgarcia** [LightBuzz/Vitruvius#4]
I'm looking for some library that allows me to track simple arm/hand gestures to use as UI for some visualizations. Is this project still maintained? If not, is there any other similar? I'm using Kinect v1.

**Comment by Vangos** [comment]
Vitruvius includes gesture recognition for version 1. Check this: https://github.com/LightBuzz/Vitruvius/blob/master/Kinect%20v1/LightBuzz.Vitruvius/GestureController.cs

**Comment by birbilis** [comment]
btw, also checkout Hospotizer's concept of space discretization (around the user) for defining gestures. I have an enhanced (and with lots of code cleanup/refactoring) version of it at http://github.com/birbilis/Hotspotizer, but have not split the gesture recognition logic into a separate library since it is still tied a lot to the UI. There are some other libraries too where one does training to teach the library gestures.
